Serialization or self study of the Book Introduction to Machine Learning with Python,
A Guid for Data Sciencetists. Coding excercses are those found in the book chapters.
by Andreas C. Müller & Sarah Guido. 

**NumPy**

NumPy is one of the fundamental packages for scientific computing in Python. It
contains functionality for multidimensional arrays, high-level mathematical func‐
tions such as linear algebra operations and the Fourier transform, and pseudorandom
number generators.

In scikit-learn, the NumPy array is the fundamental data structure. scikit-learn
takes in data in the form of NumPy arrays. Any data you’re using will have to be con‐
verted to a NumPy array. The core functionality of NumPy is the ndarray class, a
multidimensional (n-dimensional) array. All elements of the array must be of the
same type. A NumPy array looks like this:

In [3]:
# Chap 1 Introduction to Libraries

# to use numpy

import numpy as np
# create 2 arrays
x = np.array([[4,5,6],[7,8,9]])
print("x:{}".format(x))



x:[[4 5 6]
 [7 8 9]]


**SciPy**

SciPy is a collection of functions for scientific computing in Python. It provides,
among other functionality, advanced linear algebra routines, mathematical function
optimization, signal processing, special mathematical functions, and statistical distri‐
butions. scikit-learn draws from SciPy’s collection of functions for implementing
its algorithms.

In [4]:
from scipy import sparse  # scipy uses sparse matrices
import numpy as np

eye = np.eye(4) # Create a 2D NumPy array with a diagonal of ones, and zeros everywhere else
print("Numpy array:\n{}".format(eye))


Numpy array:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
# Convert the NumPy array to a SciPy sparse matrix in CSR format # Only the nonzero entries are 
# stored 
sparse_matrix = sparse.csc_matrix(eye)
print("\nSciPy sparse CSR matrix:\n{}".format(sparse_matrix))


SciPy sparse CSR matrix:
<Compressed Sparse Column sparse matrix of dtype 'float64'
	with 4 stored elements and shape (4, 4)>
  Coords	Values
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


Here is a  way to create the same sparse matrix as before, using the COO formatHere is a  way to create the same sparse matrix as before, using the COO format.


In [7]:
dt = np.ones(4)
row_indices = np.arange(4) 
col_indices = np.arange(4) 
eye_coo = sparse.coo_matrix((dt, (row_indices, col_indices))) 
print("COO representation:\n{}".format(eye_coo))

COO representation:
<COOrdinate sparse matrix of dtype 'float64'
	with 4 stored elements and shape (4, 4)>
  Coords	Values
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
