Serialization or self study of the Book Introduction to Machine Learning with Python,
A Guid for Data Sciencetists. Coding excercses are those found in the book chapters.
by Andreas C. Müller & Sarah Guido. 

**NumPy**

NumPy is one of the fundamental packages for scientific computing in Python. It
contains functionality for multidimensional arrays, high-level mathematical func‐
tions such as linear algebra operations and the Fourier transform, and pseudorandom
number generators.

In scikit-learn, the NumPy array is the fundamental data structure. scikit-learn
takes in data in the form of NumPy arrays. Any data you’re using will have to be con‐
verted to a NumPy array. The core functionality of NumPy is the ndarray class, a
multidimensional (n-dimensional) array. All elements of the array must be of the
same type. A NumPy array looks like this:

In [3]:
# Chap 1 Introduction to Libraries

# to use numpy

import numpy as np
# create 2 arrays
x = np.array([[4,5,6],[7,8,9]])
print("x:{}".format(x))



x:[[4 5 6]
 [7 8 9]]


**SciPy**

SciPy is a collection of functions for scientific computing in Python. It provides,
among other functionality, advanced linear algebra routines, mathematical function
optimization, signal processing, special mathematical functions, and statistical distri‐
butions. scikit-learn draws from SciPy’s collection of functions for implementing
its algorithms.

In [4]:
from scipy import sparse  # scipy uses sparse matrices

eye = np.eye(4) # Create a 2D NumPy array with a diagonal of ones, and zeros everywhere else
print("Numpy array:\n{}".format(eye))

Numpy array:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
